#!/usr/bin/env python3
"""Rebuild `dashboard.md` at repo root from every tracker.yaml under applications/.

Spec §6.5 / §9.4 / CLAUDE.md §2 Phase 4. `dashboard.md` is gitignored
(regenerated on every sweep) and is the one thing the user looks at
daily. Groups by status, shows next actions and last-touch recency.

Usage:

    python scripts/dashboard.py
    python scripts/dashboard.py --out /custom/path.md
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover
    sys.stderr.write("dashboard.py needs PyYAML.\n"
                     "    pip install pyyaml --break-system-packages\n")
    sys.exit(1)


REPO = Path(__file__).resolve().parent.parent
APPS = REPO / "applications"
DEFAULT_OUT = REPO / "dashboard.md"

# Grouping order. `offer` lives above `interviewing` deliberately — when
# it happens, it's the thing that should draw the eye first.
STATUS_ORDER = [
    "offer",
    "interviewing",
    "screened",
    "applied",
    "ghosted",
    "rejected",
    "withdrawn",
]

STATUS_HEADINGS = {
    "offer": "Offer",
    "interviewing": "Interviewing",
    "screened": "Screened",
    "applied": "Applied — awaiting response",
    "ghosted": "Ghosted (no movement >45d + at least one follow-up)",
    "rejected": "Rejected",
    "withdrawn": "Withdrawn",
}


def _load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open() as f:
        return yaml.safe_load(f) or {}


def _parse_iso(s: str | None) -> dt.datetime | None:
    if not s:
        return None
    try:
        return dt.datetime.fromisoformat(str(s).replace("Z", "+00:00"))
    except ValueError:
        return None


def _days_since(iso: str | None, now: dt.datetime) -> int | None:
    d = _parse_iso(iso)
    if d is None:
        return None
    if d.tzinfo is None:
        d = d.replace(tzinfo=dt.timezone.utc)
    return (now - d).days


def _last_touch_iso(tracker: dict[str, Any]) -> str | None:
    """Most recent status_history entry, or applied_on, or null."""
    history = tracker.get("status_history") or []
    if history:
        ats = [h.get("at") for h in history if h.get("at")]
        if ats:
            return str(max(ats))
    return tracker.get("applied_on")


def collect_trackers() -> list[tuple[Path, dict[str, Any]]]:
    if not APPS.exists():
        return []
    out: list[tuple[Path, dict[str, Any]]] = []
    for tracker_path in sorted(APPS.rglob("tracker.yaml")):
        if "_template" in tracker_path.parts:
            continue
        tracker = _load_yaml(tracker_path)
        if not tracker:
            continue
        out.append((tracker_path.parent, tracker))
    return out


def render(trackers: list[tuple[Path, dict[str, Any]]]) -> str:
    now = dt.datetime.now().astimezone()
    generated = now.isoformat(timespec="seconds")

    buckets: dict[str, list[tuple[Path, dict[str, Any]]]] = {s: [] for s in STATUS_ORDER}
    misc: list[tuple[Path, dict[str, Any]]] = []
    for app_dir, tracker in trackers:
        status = (tracker.get("status") or "").strip()
        if status in buckets:
            buckets[status].append((app_dir, tracker))
        else:
            misc.append((app_dir, tracker))

    # Sort each bucket by most-recent touch first.
    def _key(item: tuple[Path, dict[str, Any]]) -> str:
        _, t = item
        return _last_touch_iso(t) or ""
    for s in buckets:
        buckets[s].sort(key=_key, reverse=True)
    misc.sort(key=_key, reverse=True)

    lines: list[str] = []
    lines.append(f"# Dashboard — generated {generated}")
    lines.append("")
    lines.append(
        f"Regenerated by `scripts/dashboard.py` on every sweep. Not committed. "
        f"{len(trackers)} application(s) tracked."
    )
    lines.append("")

    open_count = sum(len(buckets[s]) for s in ("offer", "interviewing", "screened", "applied"))
    closed_count = sum(len(buckets[s]) for s in ("ghosted", "rejected", "withdrawn"))
    lines.append(f"- Open: **{open_count}**  ·  Closed: **{closed_count}**  ·  Other: **{len(misc)}**")
    lines.append("")

    for s in STATUS_ORDER:
        items = buckets[s]
        if not items:
            continue
        lines.append(f"## {STATUS_HEADINGS[s]}  ({len(items)})")
        lines.append("")
        lines.append("| Company | Role | Applied | Last touch | Next action |")
        lines.append("|---|---|---|---|---|")
        for app_dir, tracker in items:
            company = tracker.get("company") or app_dir.parent.name
            role = tracker.get("role") or "—"
            rel = app_dir.relative_to(REPO).as_posix()
            applied_on = tracker.get("applied_on") or "—"
            last_iso = _last_touch_iso(tracker)
            days = _days_since(last_iso, now)
            last_col = f"{last_iso.split('T')[0]}  ({days}d ago)" if last_iso and days is not None else "—"
            next_action = tracker.get("next_action") or "—"
            # Truncate long next_action to keep the table scannable.
            if len(next_action) > 70:
                next_action = next_action[:67] + "…"
            lines.append(
                f"| [{company}]({rel}) | {role} | {applied_on} | {last_col} | {next_action} |"
            )
        lines.append("")

    if misc:
        lines.append(f"## Other / unknown status  ({len(misc)})")
        lines.append("")
        for app_dir, tracker in misc:
            company = tracker.get("company") or app_dir.parent.name
            status = tracker.get("status") or "(unset)"
            rel = app_dir.relative_to(REPO).as_posix()
            lines.append(f"- [{company}]({rel}) — `{status}`")
        lines.append("")

    if not trackers:
        lines.append("_No applications tracked yet. Trackers live at `applications/<Company>/<role-slug>/tracker.yaml`._")
        lines.append("")

    return "\n".join(lines)


def _queue_section() -> str:
    """Run scripts/queue_status.py and capture its markdown; empty if unavailable."""
    import subprocess
    queue_status = REPO / "scripts" / "queue_status.py"
    if not queue_status.exists():
        return ""
    try:
        r = subprocess.run([sys.executable, str(queue_status)],
                           capture_output=True, text=True, cwd=str(REPO))
        if r.returncode == 0 and r.stdout.strip():
            return "\n" + r.stdout.rstrip() + "\n"
    except (FileNotFoundError, OSError):
        pass
    return ""


def _bullet_leaderboard_section() -> str:
    """Inline the leaderboard markdown if scripts/bullet_outcomes.py has produced it."""
    leaderboard = REPO / "state" / "bullet_outcomes.md"
    if leaderboard.exists():
        return "\n" + leaderboard.read_text().rstrip() + "\n"
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                        help=f"output path (default: {DEFAULT_OUT.relative_to(REPO)})")
    args = parser.parse_args()

    trackers = collect_trackers()
    md = render(trackers)
    md += _queue_section()
    md += _bullet_leaderboard_section()
    args.out.write_text(md)
    print(f"dashboard.py: wrote {len(trackers)} tracker(s) → {args.out.relative_to(REPO) if args.out.is_absolute() and args.out.is_relative_to(REPO) else args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
